services:
    cache.adapter.null:
        class: Symfony\Component\Cache\Adapter\NullAdapter
        arguments: [ ~ ] # small trick to avoid arguments errors on compile-time.

    App\Service\CbrDailySoapClientFactory:
        class: App\Service\CbrDailySoapClientFactory
        public: true
        arguments:
          [ '@parameter_bag' ]
